version: "3"

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v21.1
    restart: always
    env_file:
      - .env.local
    ports:
     - "26257:26257"
     - "8080:8080"  # visit localhost:8080 for web ui
    command: start-single-node --insecure
    volumes:
      - database-data:/cockroach/cockroach-data

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    expose:
      - "8020"
    ports:
      - "8020:8020"
    links:
      - cockroach:cockroach
    depends_on:
      - cockroach
    volumes:
      - .:/app
      - /usr/src/app/staticfiles
    entrypoint: ./start_app.sh
    env_file:
      - .env.local

volumes:
  database-data:
