# Generated by Django 3.2.9 on 2021-11-03 23:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("eks", "EKS"), ("gke", "GKE"), ("aks", "AKS")],
                        max_length=255,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                (
                    "released",
                    models.DateField(
                        blank=True,
                        help_text="Only set if known, if missing DOES NOT mean it is not available",
                        null=True,
                    ),
                ),
                (
                    "deprecated",
                    models.DateField(
                        blank=True,
                        help_text="If date of deprecation is known",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("service", "version"), name="unique_service_version"
            ),
        ),
    ]
