# Generated by Django 3.2.11 on 2022-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_version_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="service",
            field=models.CharField(
                choices=[
                    ("eks", "EKS"),
                    ("gke", "GKE"),
                    ("aks", "AKS"),
                    ("gcp_cloudsql_postgres", "GCP CloudSQL Postgres"),
                    ("gcp_cloudsql_sqlserver", "GCP CloudSQL SQL Server"),
                    ("gcp_cloudsql_mysql", "GCP CloudSQL MySQL"),
                    ("aws_elasticache_redis", "ElastiCache Redis"),
                    ("aws_elasticache_memcached", "ElastiCache Memcached"),
                    ("aws_kafka", "Kafka"),
                    ("aws_es", "ElasticSearch"),
                    ("aws_opensearch", "OpenSearch"),
                    ("aws_neptune", "Neptune"),
                    ("aws_docdb", "DocumentDB"),
                    ("aws_memorydb", "MemoryDB"),
                    ("aws_rabbitmq", "RabbitMQ"),
                    ("aws_activemq", "ActiveMQ"),
                    ("aws_aurora", "Aurora MySQL (MySQL 5.6 compatible)"),
                    ("aws_aurora_mysql", "Aurora MySQL (MySQL 5.7+ compatible)"),
                    ("aws_aurora_postgres", "Aurora Postgres"),
                    ("aws_mariadb", "MariaDB"),
                    ("aws_mysql", "MySQL"),
                    ("aws_postgres", "Postgres"),
                    ("aws_oracle_ee", "Oracle EE"),
                    ("aws_oracle_ee_cdb", "Oracle EE CDB"),
                    ("aws_oracle_se2", "Oracle SE2"),
                    ("aws_oracle_se2_cdb", "Oracle SE2 CDB"),
                    ("aws_sqlserver_ee", "SQL Server EE"),
                    ("aws_sqlserver_se", "SQL Server SE"),
                    ("aws_sqlserver_ex", "SQL Server EX"),
                    ("aws_sqlserver_web", "SQL Server Web"),
                ],
                max_length=255,
            ),
        ),
    ]
