# Generated by Django 3.2.8 on 2021-10-20 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('provider', models.CharField(choices=[('AWS', 'AWS'), ('Gcloud', 'Gcloud'), ('Azure', 'Azure')], max_length=20)),
                ('service', models.CharField(choices=[('EKS', 'EKS'), ('GKS', 'GKS'), ('AKS', 'AKS')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
