# Generated by Django 3.2.9 on 2021-11-03 23:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("eks", "EKS"), ("gke", "GKE"), ("aks", "AKS")],
                        max_length=255,
                    ),
                ),
                (
                    "disabled",
                    models.DateTimeField(
                        blank=True,
                        help_text="If populated date of unsubscribing",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
