# Generated by Django 3.2.8 on 2021-10-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="service",
            field=models.CharField(
                choices=[("eks", "EKS"), ("gke", "GKE"), ("aks", "AKS")], max_length=255
            ),
        ),
    ]
