# Generated by Django 3.2.9 on 2021-11-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(choices=[('eks', 'EKS'), ('gke', 'GKE'), ('aks', 'AKS'), ('gcp_cloud_sql', 'Cloud SQL')], max_length=255),
        ),
    ]
