name: Dev Workflow

on:
  push:
    branches:
      - master
      - feature/social-tags

jobs:
  build_deploy:
    uses: ./.github/workflows/build_deploy.yaml
    with:
      ENVIRONMENT: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
