name: Dev Workflow

on:
  push:
    branches:
      - master
      - feature/prod-release

jobs:
  build_deploy:
    uses: ./.github/workflows/build_deploy.yml@$GITHUB_REF
    with:
      environment: dev
